services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - database
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: ledger_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
